```{r Global, message = FALSE}
# Establishing the global options of the script
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE)
# Loading the libraries that will be used
library(readxl)
library(dplyr)
library(stringr)
```

```{r Data1}
# Loading the expression dataset for slide1 y slide2
# These expression datasets 
data_slide1 <- read_excel("TMAdata_format_slide1 with our parameters.xlsx", sheet = 1, na = ".")
data_slide2 <- read_excel("TMAdata_format_slide2 with our parameters.xlsx", sheet = 1, na = ".")
# Renaming/Removing conflicting columns between slide1 and slide2
data_slide1 <- data_slide1[, -2] %>% rename(TMAID = TMA_ID)
data_slide2 <- data_slide2[, -c(2, 21, 33)]

# Fixing column names
colnames(data_slide1) <- colnames(data_slide1) %>%
  str_replace_all(" ", "") %>%
  str_replace_all("#", "") %>%
  str_replace_all("%", "") %>%
  str_replace_all("0-3", "") %>%
  str_replace_all("/hpf", "") %>%
  str_replace_all("\\+", "") %>%
  str_replace_all("/K", "K")
colnames(data_slide2) <- colnames(data_slide2) %>%
  str_replace_all(" ", "") %>%
  str_replace_all("#", "") %>%
  str_replace_all("%", "") %>%
  str_replace_all("0-3", "") %>%
  str_replace_all("/hpf", "") %>%
  str_replace_all("\\+", "") %>%
  str_replace_all("/K", "K")

# Fixing column types containing the value "<1" and replacing it by "0.5"
data_slide1$PDL1inflm <- as.numeric(
  str_replace(data_slide1$PDL1inflm, "<1", "0.5"))
data_slide1$FOXP3tumorpositivity <- as.numeric(
  str_replace(data_slide1$FOXP3tumorpositivity, "<1", "0.5"))
data_slide1$Ki67oftumor <- as.numeric(
  str_replace(data_slide1$Ki67oftumor, "<1", "0.5"))
data_slide2$PDL1inflm <- as.numeric(
  str_replace(data_slide2$PDL1inflm, "<1", "0.5"))

# Merging previous datasets
data1 <- full_join(data_slide1, data_slide2)

data1 <- data1 %>%
  # Removing missing cases
  filter(!is.na(X)) %>%
  # Selecting only tumor spots
  filter(TN == "T") %>%
  # Removing unnecesary columns
  select(-c(No, TN, X, Y,
    postmcellsPDL1, totaltumorcellsPDL1,
    PDL1tm0, PDL1tm1, PDL1tm2, PDL1tm3)) %>%
  # Renaming columns
  rename(
    TMA = TMAID,
    PDL1_tumor = PDL1tumor,
    PDL1_tumor_location = PDL1locationtumor,
    PDL1_H = PDL1tmHscore,
    PDL1_stroma = PDL1inflm,
    PDL1_stroma_location = PDL1inflmaway,
    Granulomas = granuloma,
    PDL1_granulomas = PDL1ingranuloma,
    Host_response = totalhostresponse,
    FOXP3_lymph_tumor = FOXP3intraeplym,
    FOXP3_lymph_stroma = FOXP3inlymstroma,
    FOXP3_lymph_intensity = FOXP3intensitylym,
    FOXP3_tumor = FOXP3intumor,
    FOXP3_tumor_intensity = FOXP3intensitytumor,
    FOXP3_tumor_positive = FOXP3tumorpositivity,
    CD8_tumor = CD8intumor,
    CD8_Ki67_tumor = CD8Ki67intumor,
    CD8_stroma = CD8instroma,
    CD8_Ki67_stroma = CD8Ki67instroma,
    Ki67_tumor = Ki67oftumor
    )

# Recoding numeric to factor variables
data1$PDL1_tumor_location <- factor(data1$PDL1_tumor_location,
  levels = c("1", "2", "3"),
  labels = c(
    "1" = "Cytoplasmic",
    "2" = "Membranous",
    "3" = "Cytoplasmic/Membranous"
  ))
data1$PDL1_stroma_location <- factor(data1$PDL1_stroma_location,
  levels = c("0", "1"),
  labels = c(
    "0" = "Adherent to tumor",
    "1" = "Away from tumor"
  ))
data1$Granulomas <- factor(data1$Granulomas,
  levels = c("0", "1"),
  labels = c(
    "0" = "No",
    "1" = "Yes"
  ))
data1$Host_response <- factor(data1$Host_response,
  levels = c("0", "1", "2", "3"),
  labels = c(
    "0" = "No inflammatory cells",
    "1" = "Rare inflammatory cells",
    "2" = "Lymphoid aggregates",
    "3" = "Intense inflammation"
  ))
data1$FOXP3_lymph_intensity <- factor(data1$FOXP3_lymph_intensity,
  levels = c("0", "1", "2", "3"),
  labels = c(
    "0" = "No staining",
    "1" = "Weak staining",
    "2" = "Moderate staining",
    "3" = "Strong staining"
  ))
data1$FOXP3_tumor_intensity <- factor(data1$FOXP3_tumor_intensity,
  levels = c("0", "1", "2", "3"),
  labels = c(
    "0" = "No staining",
    "1" = "Weak staining",
    "2" = "Moderate staining",
    "3" = "Strong staining"
  ))
```

```{r Data2}
# Loading clinicopathologic and outcome datasets for slide1 y slide2
data_clinical1 <- read_excel("TMAdata_format_slide1 with our parameters.xlsx", sheet = 2, na = ".")
data_clinical2 <- read_excel("TMAdata_format_slide2 with our parameters.xlsx", sheet = 2, na = ".")
# Keeping clinicopathologic and outcome features only
data_clinical1 <- data_clinical1[,(1:20)]
data_clinical2 <- data_clinical2[,(1:20)]
# Removing triplicated follow-up columns and NAs rows
data_clinical1 <- data_clinical1[,-c(14,16)] %>% filter(!is.na(TMA))
data_clinical2 <- data_clinical2[,-c(14,16)] %>% filter(!is.na(TMA))
# Merging both datasets
data2 <- full_join(data_clinical1, data_clinical2)
# Removing unnecessary columns
data2 <- data2[, -c(1,3,13)]
```

```{r PDL1_tumor}
# Creating a dataframe of PDL1 expression in tumor per patient
data_PDL1_tumor <- data1 %>%
  group_by(TMA) %>%
  # Summarizing values of PDL1 expression (% and H-score)
  # We shall consider median and maximum values
  # Mean values were not used considering the Shapiro-Wilk test
  summarize(
    PDL1_median = round(median(PDL1_tumor, na.rm = TRUE), 1),
    PDL1_max = round(max(PDL1_tumor, na.rm = TRUE), 1),
    PDL1_H_median = round(median(PDL1_H, na.rm = TRUE), 1),
    PDL1_H_max = max(PDL1_H, na.rm = TRUE)
    ) %>%
  # Creating PDL1 positive variables using 1% and 5% cutoff points
  mutate(
    PDL1_pos_1_median = ifelse(PDL1_median > 1, "PDL1 positive", "PDL1 negative"),
    PDL1_pos_1_max = ifelse(PDL1_max > 1, "PDL1 positive", "PDL1 negative"),
    PDL1_pos_5_median = ifelse(PDL1_median > 5, "PDL1 positive", "PDL1 negative"),
    PDL1_pos_5_max = ifelse(PDL1_max > 5, "PDL1 positive", "PDL1 negative")
  )

# Merging the PDL1 in tumor dataset with the dataset containing the clinicopathologic and outcome features
data_PDL1_tumor <- inner_join(data2, data_PDL1_tumor, by = "TMA")
# Exporting the PDL1 in tumor dataset to CSV
write.csv(file = "data_PDL1_tumor.csv", data_PDL1_tumor, row.names = FALSE)
# Creating a dataset object for subsequent analysis
dput(data_PDL1_tumor, file = "PDL1_tumor.Rd")
```
