---
title: PDL1 positivity, maximum 1%
subtitle: PDL1 expression in tumor cells of upper tract urothelial carcinoma
output: 
  html_document: 
    keep_md: yes
    theme: united
---

```{r Data, echo = FALSE, message = FALSE, warning = FALSE}
# Establishing global options
library(knitr)
options(knitr.table.format = "markdown")
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# Loading dataset
data <- dget("PDL1_tumor.Rd")
# Transforming character variables to factor variables
col_factor <- c(1:23)
col_factor <- col_factor[-c(3,13,16:19)]
for (i in col_factor){
  data[,i] <- as.factor(data[,i])
}
# Loading libraries
library(ggplot2)
library(dplyr)
library(simpleR)
# ggplot2 theme
gtheme <- theme(
  plot.title = element_text(size = 18, vjust = 1.5),
  axis.title.x = element_blank(),
  axis.text.x = element_text(color = "black"),
  axis.title.y = element_text(size = 16, vjust = 1.5),
  axis.text.y = element_text(color = "black")
)
# ggplot2 theme3
gtheme3 <- theme(
  plot.title = element_text(size = 20, vjust = 1.5),
  axis.title.x = element_text(vjust = -.5, size = 16),
  axis.text.x = element_text(color = "black"),
  axis.title.y = element_text(vjust = 1.5, size = 16),
  axis.text.y = element_text(color = "black"),
  legend.title = element_blank()
)
# ggplot2 survival curves using ggfortify
library(ggfortify)
library(survival)
gsurv <- function(FU, outcome, status){
  fit <- survfit(Surv(FU, as.numeric(outcome)) ~ status)
  autoplot(fit, conf.int = FALSE, censor = FALSE, surv.size = 1) +
    ylab("Survival") +
    xlab("Follow-up") +
    scale_colour_discrete(labels = levels(status)) +
    gtheme3
}
```

```{r Outcome}
# Defining the outcome
data$outcome <- data$PDL1_pos_1_max
```

```{r PDL1_pos_1_max}
# Gender
p <- with(data, fisher.test(outcome, gender)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = gender, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 45), breaks = seq(0, 45, 10)) +
  annotate("text", x = 1.5, y = 45, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by patients' sex") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(gender, outcome))
# Age
p <- with(data, wilcox.test(age ~ outcome)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(y = age, x = outcome, fill = outcome)) +
  geom_boxplot(color = "black") +
  ggtitle("PDL1 positivity by patients' age") +
  scale_y_continuous() +
  ylab("Age, in years") +
  scale_y_continuous(limits = c(45, 90)) +
  annotate("text", x = 1.5, y = 90,
           label = paste("P value =", p)) +
  gtheme + theme(legend.position = "none")
with(data, descriptive.numerical.group(age, outcome))
# Location
p <- with(data, fisher.test(outcome, location)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = location, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10)) +
  annotate("text", x = 2, y = 35, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by tumor location") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(location, outcome))
# pt
data$pt <- factor(data$pt, levels = c("pTa", "pT1", "pT2", "pT3", "pT4"))
p <- with(data, fisher.test(outcome, pt)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = pt, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 40, 10)) +
  annotate("text", x = 3, y = 35, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by pT stages") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(pt, outcome))
# high_pt
p <- with(data, fisher.test(outcome, high_pt)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = high_pt, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, 10)) +
  annotate("text", x = 1.5, y = 40, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by high pT stage") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(high_pt, outcome))
# grade
p <- with(data, fisher.test(outcome, grade)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = grade, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10)) +
  annotate("text", x = 2, y = 35, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by histologic grades") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(grade, outcome))
# high_grade
p <- with(data, fisher.test(outcome, high_grade)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = high_grade, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, 10)) +
  annotate("text", x = 1.5, y = 60, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by high histologic grade") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(high_grade, outcome))
# lymph
data_nona <- data %>% filter(!is.na(lymph))
p <- with(data_nona, fisher.test(outcome, lymph)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data_nona, aes(x = lymph, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 55), breaks = seq(0, 55, 10)) +
  annotate("text", x = 1.5, y = 55, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by lymph node metastasis") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data_nona, descriptive.categorical.group(lymph, outcome))
# lvi
p <- with(data, fisher.test(outcome, lvi)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = lvi, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 45), breaks = seq(0, 45, 10)) +
  annotate("text", x = 1.5, y = 45, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by lymphovascular invasion") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(lvi, outcome))
# BTrecurrence
data_nona <- data %>% filter(!is.na(BTrecurrence))
p <- with(data_nona, fisher.test(outcome, BTrecurrence)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data_nona, aes(x = BTrecurrence, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 45), breaks = seq(0, 45, 10)) +
  annotate("text", x = 1.5, y = 45, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by local tumor recurrence") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data_nona, descriptive.categorical.group(BTrecurrence, outcome))
# progression
data_nona <- data %>% filter(!is.na(progression))
p <- with(data_nona, fisher.test(outcome, progression)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data_nona, aes(x = progression, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0, 35, 10)) +
  annotate("text", x = 1.5, y = 35, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by tumor progression") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data_nona, descriptive.categorical.group(progression, outcome))
# fu_mo
p <- with(data, wilcox.test(fu_mo ~ outcome)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(y = fu_mo, x = outcome, fill = outcome)) +
  geom_boxplot(color = "black") +
  ggtitle("PDL1 positivity by follow-up length") +
  scale_y_continuous() +
  ylab("Follow-up, in months") +
  scale_y_continuous(limits = c(0, 180), breaks = seq(0, 180, 24)) +
  annotate("text", x = 1.5, y = 180,
           label = paste("P value =", p)) +
  gtheme + theme(legend.position = "none")
with(data, descriptive.numerical.group(fu_mo, outcome))
# dod
p <- with(data, fisher.test(outcome, dod)$p.value)
p <- format(p, digits = 2, scientific = TRUE, justify = "centre")
ggplot(data, aes(x = dod, fill = outcome)) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_y_continuous(limits = c(0, 45), breaks = seq(0, 45, 10)) +
  annotate("text", x = 1.5, y = 45, label = paste("P value =", p)) +
  ggtitle("PDL1 positivity by cancer-related death") +
  ylab("No. patients") +
  gtheme + theme(legend.title = element_blank())
with(data, descriptive.categorical.group(dod, outcome))
# Survival dod
ht <- with(data, survdiff(Surv(fu_mo, as.numeric(dod)) ~ outcome))
p <- format(pchisq(ht$chisq, df = 1, lower.tail = FALSE), digits = 2, scientific = TRUE, justify = "centre")
with(data, gsurv(fu_mo, dod, outcome)) +
  ggtitle("Survival curves of cancer-related death \nby PDL1 positivity") +
  ylab("Survival") +
  xlab("Follow-up, months") +
  scale_x_continuous(breaks = seq(0, 180, 24)) +
  annotate("text", label = paste("P value =", p), x = 25, y = .6) +
  theme(legend.position = c(.875, .875))
```

```{r Regression_Tables}
# Creating age group
data <- data %>%
  mutate(
    age_group = ifelse(age > median(age), "Older", "Younger"))
# Dropping levels with pelvis-ureter tumors
data$location2 <- data$location
data$location2[data$location == "Pelvis-Ureter"] <- NA
data$location2 <- droplevels(data$location2)
# Creating list of predictors and associated varlabels
predictors <- with(data, list(
  "Patient's sex" = gender,
  "Patient's age group" = age_group,
  "Tumor location (pelvis vs ureter)" = location2,
  "High pT (>pT2) stage" = high_pt,
  "High histologic grade" = high_grade,
  "Lymph node metastasis" = lymph,
  "Lymphovascular invasion" = lvi,
  "PDL1 positivity" = outcome
))
varlabels <- names(predictors)
```

# Odds ratios for local tumor recurrence
```{r OR_BTrecurrence}
outcome <- data$dod
logistic.table(outcome, predictors, varlabels)
```

# Odds ratios for tumor progression
```{r OR_progression}
outcome <- data$progression
logistic.table(outcome, predictors, varlabels)
```

# Odds ratios for cancer-related death
```{r OR_dod}
outcome <- data$dod
logistic.table(outcome, predictors, varlabels)
```

# Hazard ratios for cancer-related death
```{r HR_dod}
fu <- data$fu_mo
cox.table(outcome, fu, predictors, varlabels)
```

